#!/bin/bash

#Globals
help=$(cat <<HELP
Bash Script Manager

Usage: bsm [OPTIONS] ...

Options:
    -c | --create
	Add new script(s) to your personal scripts. Specify a file extension to use a specific scripting language. Bash is default and doesn't require a file extension.
	Available: .js, .py, .rb, .cl

    -l | --list
	Show list of available personal scripts

    -L | --link
	Create a shortcut executable to an existing script

    -o | --open
	Open a script for editing (ONLY PERSONAL SCRIPTS LOCATED AT /scripts).
    Makes a new script respective to the env path (file ext). Bash creation does not require this.
    Will still open respective file even if env path is provided

    -r | --remove
	Remove script(s) from personal scripts (DOES NOT TOUCH SYSTEM EXECUTABLES)

    -a | --add
    Add an external script directly to bsm

    -v | --version
        Show version

    -h | --help
        Show this screen
    
HELP
);
version="1.1.0";

#INIT
if [[ ! -d /scripts ]]; then
    echo "FIRST TIME SETUP! Installing Dependencies..."
    #Allow use of /var/log to programs
    sudo mkdir /var/log/bsm;
    touch /var/log/bsm/err.log 2>/dev/null;
    sudo chmod 766 /var/log/bsm/err.log;

    #Make folders
    sudo mkdir /scripts;
    # sudo mkdir /scripts/node
    # sudo mkdir /scripts/python
    # sudo mkdir /scripts/ruby
    # sudo mkdir /scripts/lisp
    #Allow rwx permissions to scripts
    sudo chmod 777 -R /scripts;
    #Also update PATH for first-time use
    PATH="$PATH:/scripts:/scripts/node:/scripts/python:/scripts/ruby:/scripts/lisp"
    
    echo "Installed!"
fi

#Go thru args
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
    case "$1" in
        -c | --create )
            shift
            name=$1
            if [[ ! -e "/scripts/node/${name%.**}" && ! -e "/scripts/python/${name%.**}" && ! -e "/scripts/$name" ]]; then

                #Check for other types of executeable scripts
                if [[ "$name" =~ ".py" ]]; then
                    #Make python folder and executable (Install python if not installed)
                    if [[ ! -d "/scripts/python" ]]; then
                        echo "Installing Python and setting up dependencies..."
                        mkdir /scripts/python 2>/dev/null
                        sudo apt-get install -y python3-pip 2>/dev/null
                    fi
                    touch "/scripts/python/${name%.py}" && chmod 757 "/scripts/python/${name%.py}"
                    printf "#!/bin/env python3\n\n#Write script code" > "/scripts/python/${name%.py}"
                    if [[ -e "/scripts/python/${name%.py}" ]]; then
                        echo "Script Created!"
                    fi
                elif [[ "$name" =~ ".js" ]]; then
                    #Make Nodejs folder, exe, installation
                    if [[ ! -d "/scripts/node" ]]; then
                        echo "Installing Node.js and dependencies..."
                        mkdir /scripts/node 2>/dev/null
                        sudo snap install --edge node --classic 2>/dev/null
                    fi
                    touch "/scripts/node/${name%.js}" && chmod 757 "/scripts/node/${name%.js}"
                    printf "#!/bin/env node\n\n//Write script code" > "/scripts/node/${name%.js}"
                    if [[ -e "/scripts/node/${name%.js}" ]]; then
                        echo "Script Created!"
                    fi
                elif [[ "$name" =~ ".rb" ]]; then
                    #Ruby folder, exe, install
                    if [[ ! -d "/scripts/ruby" ]]; then
                        echo "Installing Ruby and dependencies..."
                        mkdir /scripts/ruby 2>/dev/null
                        sudo apt install ruby-full 2>/dev/null
                    fi
                    touch "/scripts/ruby/${name%.rb}" && chmod 757 "/scripts/ruby/${name%.rb}"
                    printf "#!/bin/env ruby\n\n//Write script code" > "/scripts/ruby/${name%.rb}"
                    if [[ -e "/scripts/ruby/${name%.rb}" ]]; then
                        echo "Script Created!"
                    fi
                elif [[ "$name" =~ ".cl" ]]; then
                    #LISP folder, exe, install
                    if [[ ! -d "/scripts/lisp" ]]; then
                        echo "Installing CommonLISP and dependencies..."
                        mkdir /scripts/node 2>/dev/null
                        sudo apt install sbcl 2>/dev/null
                    fi
                    touch "/scripts/lisp/${name%.cl}" && chmod 757 "/scripts/lisp/${name%.cl}"
                    printf "#!/bin/env sbcl\n\n//Write script code" > "/scripts/node/${name%.cl}"
                    if [[ -e "/scripts/lisp/${name%.cl}" ]]; then
                        echo "Script Created!"
                    fi
                else #Deal with Bash
                    touch "/scripts/$name" && chmod 757 "/scripts/$name"
                    printf "#!/bin/bash\n\n#Write script code" > "/scripts/$name"
                    if [[ -e "/scripts/$name" ]]; then
                        echo "Script Created!"
                    fi
                fi
            else
                echo "Script with that name exists! Keeping Original..."
                echo "Would you like to open this script?"
                read yn
                if [[ "${yn,}" =~ "y" ]]; then
                    bsm -o "${name%.**}"
                fi
            fi
            ;;
        -o | --open )
            shift
            name=$1
            if [[ -e "/scripts/lisp/${name%.**}" || -e "/scripts/ruby/${name%.**}" || -e "/scripts/python/${name%.**}" || -e "/scripts/node/${name%.**}" || -e "/scripts/${name%.**}" ]]; then
                find -L /scripts -name "${name%.**}" -exec sudo nano {} \;
            else
                bsm -c "$name" -o "${name%.**}"
            fi
            exit;;
        -r | --remove )
            shift
            name=( "$@" )
            for n in $name; do
                if [[ -e "/scripts/${n%.**}" ]]; then
                    rm "/scripts/${n%.**}" 2> /var/log/bsm/err.log
                    if [[ ! -e "/scripts/${n%.**}" ]]; then
                        echo "Script Removed!"
                    else
                        echo "Unable to remove script, refer to /var/log/bsm/err.log for details"
                    fi
                else
                    #Check for other executables
                    if [[ -e "/scripts/python/${n%.**}" ]]; then
                        rm "/scripts/python/${n%.**}" 2> /var/log/bsm/err.log
                        if [[ ! -e "/scripts/python/${n%.**}" ]]; then
                            echo "Script(s) Removed!"
                        else
                            echo "Unable to remove script, refer to /var/log/bsm/err.log for details"
                        fi
                    elif [[ -e "/scripts/node/${n%.**}" ]]; then
                        rm "/scripts/node/${n%.**}" 2> /var/log/bsm/err.log
                        if [[ ! -e "/scripts/node/${n%.**}" ]]; then
                            echo "Script(s) Removed!"
                        else
                            echo "Unable to remove script, refer to /var/log/bsm/err.log for details"
                        fi
                    elif [[ -e "/scripts/ruby/${n%.**}" ]]; then
                        rm "/scripts/ruby/${n%.**}" 2> /var/log/bsm/err.log
                        if [[ ! -e "/scripts/ruby/${n%.**}" ]]; then
                            echo "Script(s) Removed!"
                        else
                            echo "Unable to remove script, refer to /var/log/bsm/err.log for details"
                        fi
                    elif [[ -e "/scripts/lisp/${n%.**}" ]]; then
                        rm "/scripts/lisp/${n%.**}" 2> /var/log/bsm/err.log
                        if [[ ! -e "/scripts/lisp/${n%.**}" ]]; then
                            echo "Script(s) Removed!"
                        else
                            echo "Unable to remove script, refer to /var/log/bsm/err.log for details"
                        fi
                    else
                        echo "Script doesn't exist!"
                    fi
                fi
            done
            exit;;
        -L | --link )
            shift
            file=$1
            shift
            name=$1
            sudo chmod 757 "$file"
            ln -s -t /scripts "$file" "$name" 2> /var/log/bsm/err.log
            if [[ -e "/scripts/$name" ]]; then
                echo "Script Linked!"
            else
                echo "Failed to Link!"
            fi
            ;;
        -a | --add )
            shift
            name=$1
            bsm -c "$name"
            scriptpath="/scripts"
            if [[ "$name" =~ ".js" ]]; then
                scriptpath="$scriptpath/node"
            elif [[ "$name" =~ ".py" ]]; then
                scriptpath="$scriptpath/python"
            elif [[ "$name" =~ ".rb" ]]; then
                scriptpath="$scriptpath/ruby"
            elif [[ "$name" =~ ".cl" ]]; then
                scriptpath="$scriptpath/lisp"
            fi
            cat < find -L -type f ~ -name "$name" >> "$scriptpath/${name%.**}"
            ;;
        -l | --list )
            echo "Available Scripts:"
            ls -pR1 /scripts | grep -v / | tr -s '\n' ' ' | tr ' ' '\n' | xargs -i echo "- {}"
            exit;;
        -v | --version )
            echo "$version"
            exit;;
        -h | --help )
            echo "$help"
            exit;;
        * )
            echo "$help"
            exit;;
    esac
    shift
done
