#!/bin/bash

#This script runs the general install for BSM
echo "Installing..."
sudo cp "$(find -name "bsm")" /usr/local/bin/bsm
sudo chmod 755 /usr/local/bin/bsm
echo "Updating PATH..."
if [[ "$(cat ~/.bashrc | tail -n 1)" == "fi" ]]; then
  echo "export PATH=\"$PATH:/scripts:/scripts/node:/scripts/python:/scripts/ruby:/scripts/lisp\"" >> ~/.bashrc
fi
echo "Setting up logging and scripts folders..."
sudo mkdir /scripts
sudo chmod 777 /scripts
sudo touch /var/log/bsm_err_log.log
sudo touch /var/log/bsm_log.log
sudo chmod 766 /var/log/bsm_err_log.log
sudo chmod 766 /var/log/bsm_log.log

#This should setup BSM, logging is sent to stdout to check for any errors
echo "BSM has been successfully installed! Run"
echo ""
echo "\`source ~/.bashrc\`"
echo ""
echo "for the changes to take effect!"