#!/bin/bash

### BSM: reverse shell ###

. /bsm/.bsm-vars
. /bsm/.bsm-funcs

# Welcome message
echo "Welcome to BSM shell!"

# Start shell
while true; do
  read -p "bsm> " stdin
  if [[ "${stdin,}" == "exit" || "${stdin,}" == "quit" ]]; then
    exit
  fi
  search_cmds "${stdin,}"
done