#!/bin/bash

### BSM: reverse shell ###

repo="$(find ~ -type d -name "Bash-Script-Manager")"
if [ -e /bsm/.vars ]; then
  # echo "Loading vars from BSM assets"
  . /bsm/.vars
elif [ -e ~/bsm/.vars ]; then
  # echo "Loading vars from BSM assets (Git Bash)"
  . ~/bsm/.vars
else
  # echo "Loading vars from repo"
  . $repo/.vars # Fallback to repo version
fi
. $BSM_ROOT/.funcs

# Welcome message
echo "Welcome to BSM shell!"

# Start shell
while true; do
  read -p "bsm> " stdin
  if [[ "${stdin,}" == "exit" || "${stdin,}" == "quit" ]]; then
    exit
  elif [[ "${stdin,}" == "pass" ]]; then
    continue
  elif [[ "${stdin,}" =~ "pass" ]]; then
    bash -c "$(echo "${stdin,}" | cut -d ' ' -f2-)"
  else
    search_cmds "${stdin,}"
  fi
done