#!/bin/bash

############### REPO Installer ################
#    Script designed to wrap a GitHub repo    #
#    Allows for program installation as if    #
#    coming from a package manager like apt   #
#  Requires a ri.cfg file so the script knows #
# what files to copy where and where the PATH #
#        will point to for said program       #
###############################################

# Functions
parse() {
  local installDesc=`echo "$1" | cut -d '>' -f1`
  local toBeCopied=`echo "$1" | cut -d '>' -f2`
  local destination=`echo "$1" | cut -d '>' -f3`
  local onTrue=`echo "$1" | cut -d '>' -f4`
  local onFalse=`echo "$1" | cut -d '>' -f5`
  [[ $destination =~ "BIN" ]] && destination=$(echo "$destination" | sed "s|BIN|$BIN|g")
  [[ $destination =~ "HOME" ]] && destination=$(echo "$destination" | sed "s|HOME|$HOME|g")
  [[ $destination =~ "ROOT" ]] && destination=$(echo "$destination" | sed "s|ROOT|$ROOT|g")
  case $installDesc in
    f ) # Copy file
      echo "Copying '$toBeCopied' to $destination/$toBeCopied"
      $sudo cp $toBeCopied $destination/
      ;;
    d ) # Copy directory
      echo "Copying folder '$toBeCopied' to $destination"
      $sudo cp -r $toBeCopied $destination
      ;;
    r ) # Recursively copy directory contents
      echo "Copying folder contents and subfolders of '$toBeCopied' to $destination"
      $sudo cp -r $toBeCopied $destination/
      ;;
    x ) # Source a script into RepoInstaller
      echo "Executing file '$toBeCopied' in directory $PWD"
      source ./$toBeCopied $destination
      ;;
    e ) # Write to Console
      echo "$1" | cut -d '>' -f2
      ;;
    c ) # Conditional copy
      # Use destination to hold condition (Satisfy BASH if condition set for '[[' )
      [[ $onTrue =~ "BIN" ]] && onTrue=$(echo "$onTrue" | sed "s|BIN|$BIN|g")
      [[ $onTrue =~ "HOME" ]] && onTrue=$(echo "$onTrue" | sed "s|HOME|$HOME|g")
      [[ $onTrue =~ "ROOT" ]] && onTrue=$(echo "$onTrue" | sed "s|ROOT|$ROOT|g")
      [[ $onFalse =~ "BIN" ]] && onFalse=$(echo "$onFalse" | sed "s|BIN|$BIN|g")
      [[ $onFalse =~ "HOME" ]] && onFalse=$(echo "$onFalse" | sed "s|HOME|$HOME|g")
      [[ $onFalse =~ "ROOT" ]] && onFalse=$(echo "$onFalse" | sed "s|ROOT|$ROOT|g")
      if [[ $destination ]]; then cp $toBeCopied $onTrue/; else cp $toBeCopied $onFalse/; fi
      ;;
    m ) # Make a directory (PATH starts at $ROOT directory)
      if [[ "$toBeCopied" == "f" ]]; then
        echo "Making file $destination"
        $sudo touch -i $ROOT/$destination
      else
        echo "Making directory $toBeCopied"
        $sudo mkdir $ROOT/$toBeCopied 2>> /dev/null
      fi
      ;;
    * )
      echo "Flag '$installDesc' doesn't exist!"
      ;;
  esac
}

BIN=~/bin
# [[ "$1" == '-v' ]] && ROOT=$1 || ROOT=$HOME
[ `command -v sudo` ] && sudo=sudo || sudo=""
if [ "$1" == '-v' ]; then
  echo "v1.0.0"
  exit
else
  [[ "$1" == "" ]] && ROOT=$HOME || ROOT="$1"
fi

# Default action is to move every file in the folder that doesn't match the global ignore rule
# Default destination is the user's ~/bin folder
[ ! -e $(pwd)/.git ] && `echo "Not a git repository!" && exit`
if [ -e ./ri.cfg ]; then
  # Read cfg line by line to determine destination for program files
  if [[ `cat ./ri.cfg | wc -l` == "1" ]]; then
    parse `cat ./ri.cfg | sed -E 's/\s*>\s*/>/g'`
  else
    IFS=''
    while read line; do
      # [[ -z "$line" || "$line" == "\r\n" ]] && continue
      # Preemptively grab comments before processing
      [[ "$line" =~ "#" ]] && continue
      if [[ "$line" =~ ">" ]]; then
        line=$(echo "$line" | sed -E 's/\s*>\s*/>/g' )
        # echo "$line"
        # Do install parse
        parse $line
      else continue; fi
    done < ./ri.cfg
  fi
else
  cp -r ./* ~/bin
fi
